p1	db 'Intel486™ DX processors', 0
p2	db 'Intel486 SX processors', 0
p3	db 'Intel487™ processors', 0
p4	db 'IntelDX2™ processors', 0
p5	db 'IntelDX2 OverDrive ® processors', 0
p6	db 'Intel486 SL processor', 0
p7	db 'IntelSX2™ processors', 0
p8	db 'Write-Back Enhanced IntelDX2 processors', 0
p9	db 'IntelDX4 processor', 0
p10	db 'IntelDX4 OverDrive processors', 0
p11	db 'Pentium ® processors (60, 66)', 0
p12	db 'Pentium processors (75, 90, 100, 120, 133, 150, 166, 200)', 0
p13	db 'Pentium OverDrive processor for Pentium processor (60, 66)', 0
p14	db 'Pentium OverDrive processor for Pentium processor (75, 90, 100, 120, 133)', 0
p15	db 'Pentium OverDrive processors for Intel486 processor-based systems', 0
p16	db 'Pentium processor with MMX™ technology (166, 200)', 0
p17	db 'Pentium OverDrive processor with MMX™ technology for Pentium processor (75, 90, 100, 120, 133)', 0
p18	db 'Pentium Pro processor', 0
p19	db 'Pentium II processor, model 3', 0
p20	db 'Pentium II processor, model 5, Pentium II', 0
p21	db 'Intel Celeron processor, model 5', 0
p22	db 'Intel Celeron processor, model 6', 0
p23	db 'model 7', 0
p24	db 'Intel Celeron processor, model 8', 0
p25	db 'Pentium III Xeon processor, model A', 0
p26	db 'Pentium III processor, model B', 0
p27	db 'Intel Pentium II OverDrive processor', 0
p28	db 'Intel Pentium 4 processor or Intel Xeon processor', 0
